---

- hosts: all
  become: true
  tasks: 

  - name: install Samba package
    apt:
      name: 
        - samba
      state: latest

  - name: Modify smb.conf
    lineinfile: dest=/etc/samba/smb.conf insertafter="[global]" state=present backup=yes backrefs=yes
    with_items:
      - 'workgroup = DEVELOPERTOWN'
      - 'winbind use default domain = yes'
      - 'security = ads'
      - 'ntlm auth = mschapv2-and-ntlmv2-only'
      - 'realm = developertown.com'